### ISSUE TITLE
redmine not starting up after installing the plugin - TemplateError (No plugin called 'redmine_time_tracker' 

### ISSUE THREAD

**Issue by beebase** [fernandokosh/redmine_time_tracker#29]
This is what I get from the redmine log.
When I remove the plugin folder, everything works fine again.
Any ideas?

Processing WelcomeController#index (for 83.80.249.221 at 2010-10-20 22:02:08) [GET]
  Parameters: {"action"=>"index", "controller"=>"welcome"}
Rendering template within layouts/base
Rendering welcome/index

ActionView::TemplateError (No plugin called 'redmine_time_tracker' - please use the full name of a loaded plugin.) on line #19 of app/views/layouts/base.rhtml:
16:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
17:     </style>
18: <![endif]-->
19: <%= call_hook :view_layouts_base_html_head %>
20: 
21: <%= yield :header_tags -%>
22: </head>

```
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:144:in `call_hook'
app/views/layouts/base.rhtml:19:in `_run_rhtml_app47views47layouts47base46rhtml'
```

Rendering /Applications/redmine/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by beebase** [comment]
solved:
renamed the extracted plugin folder to "redmine_time_tracker"
