### ISSUE TITLE
Error when trying to configure

### ISSUE THREAD

**Issue by fmluizao** [fernandokosh/redmine_time_tracker#78]
When I go to Plugins > Configure, I get the following error:

``` ruby
  ActionView::TemplateError (PGError: ERROR:  invalid input syntax for integer: "status_transitions"
  LINE 1: ...M "issue_statuses" WHERE ("issue_statuses"."id" = 'status_tr...
                                                             ^
  : SELECT * FROM "issue_statuses" WHERE ("issue_statuses"."id" = 'status_transitions')  LIMIT 1) on line #26 of vendor/plugins/redmine_time_tracker/app/views/time_trackers/_status_transition_list.rhtml:
  23:                 <% else %>
  24:                     <% transitions.each do |from, to| %>
  25:                         <tr class="<%=cycle('odd', 'even') %>">
  26:                             <% status_from = status_from_id(from) %>
  27:                             <% status_to = status_from_id(to) %>
  28:                             <% if status_from.nil? or status_to.nil? %>
  29:                                 <% has_zombie = true %>

    vendor/plugins/redmine_time_tracker/app/helpers/application_helper.rb:7:in `status_from_id'
    vendor/plugins/redmine_time_tracker/app/views/time_trackers/_status_transition_list.rhtml:26:in `_run_rhtml_vendor47plugins47redmine_time_tracker47app47views47time_trackers47_status_transition_list46rhtml_locals_object_status_transition_list_transitions'
    vendor/plugins/redmine_time_tracker/app/views/time_trackers/_status_transition_list.rhtml:24:in `each'
    vendor/plugins/redmine_time_tracker/app/views/time_trackers/_status_transition_list.rhtml:24:in `_run_rhtml_vendor47plugins47redmine_time_tracker47app47views47time_trackers47_status_transition_list46rhtml_locals_object_status_transition_list_transitions'
    vendor/plugins/redmine_time_tracker/app/views/settings/_time_tracker.rhtml:19:in `_run_rhtml_vendor47plugins47redmine_time_tracker47app47views47settings47_time_tracker46rhtml_locals_object_settings_time_tracker'
    app/views/settings/plugin.rhtml:6
    app/views/settings/plugin.rhtml:4:in `_run_rhtml_app47views47settings47plugin46rhtml'
```

Version: Redmine 1.2.1.stable (PostgreSQL)

Maybe I did something wrong on installation?

**Comment by delaitre** [comment]
Which version of the plugin do you use (last stable release or development version)?

**Comment by fmluizao** [comment]
Development version.

**Comment by tom0815** [comment]
I just installed the 0.4 on a redmine 1.3.1 and also stumbled upon an error when trying to configure the plugin:

```
Processing SettingsController#plugin (for 77.189.183.146 at 2012-09-20 15:30:32) [GET]
Parameters: {"controller"=>"settings", "id"=>"redmine_time_tracker", "action"=>"plugin"}
Rendering template within layouts/admin
Rendering settings/plugin
ActionView::TemplateError (undefined method `has_key?' for "status_transitions":String) on line #64 of Vendor/plugins/redmine_time_tracker/app/views/time_trackers/_status_transition_list.rhtml:
61:     <% if edit_allowed %>
62:         <div>
63:             <%= label_tag 'new-transition-from', l(:time_tracker_settings_new_transition_from) %>
64:             <%= select_tag 'new-transition-from', new_transition_from_options(transitions) %>
65:             <%= label_tag 'new-transition-to', l(:time_tracker_settings_new_transition_to) %>
66:             <%= select_tag 'new-transition-to', new_transition_to_options %>
67:             <%= link_to_remote l(:time_tracker_settings_new_transition_add),
vendor/plugins/redmine_time_tracker/app/helpers/application_helper.rb:21:in `new_transition_from_options'
vendor/plugins/redmine_time_tracker/app/helpers/application_helper.rb:20:in `each'
vendor/plugins/redmine_time_tracker/app/helpers/application_helper.rb:20:in `new_transition_from_options'
vendor/plugins/redmine_time_tracker/app/views/time_trackers/_status_transition_list.rhtml:64:in `_run_rhtml_vendor47plugins47redmine_time_tracker47app47views47time_trackers47_status_transition_list46rhtml_locals_object_status_transition_list_transitions'
vendor/plugins/redmine_time_tracker/app/views/settings/_time_tracker.rhtml:19:in`_run_rhtml_vendor47plugins47redmine_time_tracker47app47views47settings47_time_tracker46rhtml_locals_object_ settings_time_tracker'
app/views/settings/plugin.html.erb:6
app/views/settings/plugin.html.erb:4
passenger (3.0.11) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.11) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.11) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
passenger (3.0.11) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.11) helper-scripts/passenger-spawn-server:99
Rendering /data/web_applications/redmine-1.3.1/public/500.html (500 Internal Server Error)
```
